### ISSUE TITLE
Is the ptt-beauty crawler data operated separately? 

### ISSUE THREAD

**Issue by pyfbsdk59** [kkdai/ptt-beauty-linebot#2]
I found that you used firebase as the database, and there is a database_url environment variable in the code. However, there isn't yet anything about it in README.md. (I think you will add it in the future.) Moreover, how do you scrape the ptt-beauty data into the database? Thank you!

**Comment by kkdai** [comment]
I will only save the personal favorite list  (which is the ptt-beauty article ID list) in DB.
Users can easily add and remove their favorite article ID.
Refer https://github.com/kkdai/linebot-ptt-beauty-clone for the PostGresSQL version.

Feel free to help me implement the firebase version and send a pull request to make it better.

**Comment by pyfbsdk59** [comment]
Thank you for the reply.
